### ISSUE TITLE
Design the UI for the contact us page

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/club-website-frontend#14]
Design the UI of the contact us page. Including the following elements: 

general contact
each board member's contact (currently 3 of them)
board members' picture
anything else you think fits (perhaps a place where people can directly email us?)

**Comment by calvinfong26** [comment]
https://www.figma.com/file/Og5PlGnzTNwED7NEGzsGfp/Contact-Us-Page?node-id=0%3A1
