### ISSUE TITLE
Quality Assurance: eric-homepage

### ISSUE THREAD

**Issue by ericsheng495** [hicodingclub/club-website-frontend#20]
In a google doc document and comment on some potential changes to our website. These changes are published on the testing server. You can access it through the link below.

http://34.226.30.20:4000 

The testing server does not contain all of the posts, don't worry about it. Focus on the different UI components instead of the contents.

Here are the changes:
1. title bar
2. homepage animation

Here are some other things you can do:
1. Document the changes from the published website and express whether you like them or not. Why or why not.
2. Look for bugs and other errors such as spelling and grammar errors
3. Test website responsiveness(How the website will react to different screen sizes, you can test that by dragging the window of your browser to different sizes)
4. Think of more creative improvements/components (you can check out other big company's websites such as apple, tesla, walmart, whatever)

**Comment by calvinfong26** [comment]
https://docs.google.com/document/d/1GAhCLCOTWwLbgqcEfIEkdwvPxeAcQ9FSRrsN7tFVcwQ/edit

**Comment by ericsheng495** [comment]
https://docs.google.com/document/d/14bNYBvZAxtSoR42TL7YaFTYJ9LGHBI5nDSZc1sckGpI/edit?usp=sharing
