### ISSUE TITLE
Write a news post about the April 26 UI Design Workshop

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/club-website-frontend#25]
This task is limited to participants and hosts of the April 26 UI Design Workshop

Write a paragraph or two about the April 26 UI Design Workshop on a google doc. You can be creative and anything can be included. You cal talk about, but not limited to:
* material William went over during the workshop
* what you learned and you personal experience within the workshop
* the environment of the workshop or the workshop as a whole
* Anything else

The post you write will be posted as a news in the news section on our club's website

Due Date: Sunday, May 3rd

**Comment by WilliamShih1234** [comment]
The workshop was pretty cool and had more people than I expected. I think maybe it would have been better if everyone was trying to follow what I was doing at the same time I was demonstrating so I could answer any questions they have or help them with anything. I’m not sure how this would work like if people can share their screens all at the same time or maybe we could all collaborate on a single figma project at once (I think this is a better idea). I think maybe making a project together would be better too and maybe assign people different tasks to complete something cool by the end of the workshop. Also the length of the workshop I was not sure about. It was about 20-25 minutes but probably a little bit longer would be better but maybe people would get bored. This could be fixed if I made sure they were trying the things I tell them on the same figma project.

**Comment by WilliamShih1234** [comment]
https://docs.google.com/document/d/1StSzdGE68uSR39_bHueDwM5kMNaIj7OAF1aKO4yj7Ww/edit?usp=sharing
