### ISSUE TITLE
UI Design: Completed Projects/Customers Section

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/club-website-frontend#28]
create a section about the projects we have completed before and the companies that are using the websites we developed. This section will be put at the bottom of the homepage. This section should be very simple and straightforward. Check out [this weather API website](https://weatherstack.com) as an example. Paste the link to your Figma design below.

**Number of people: unlimited**
**Volunteer Hours: 0.5 hour**

**Comment by WilliamShih1234** [comment]
https://www.figma.com/file/p8cUqdeYkjgsg1QwDNvurH/Completed-Projects-Customers-Section?node-id=0%3A1

**Comment by calvinfong26** [comment]
https://www.figma.com/file/vpzMOFXgBIj6PXDTf3u3DN/Projects%2FCustomers-Section?node-id=0%3A1
