### ISSUE TITLE
UI Design: Redesign the top section of the Members page

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/club-website-frontend#29]
The Top part of the Members page at https://hicodingclub.org/members is not very visually appealing. Please design a new one. **Be creative**. If you want a certain type of picture to be shown, don't worry about the picture itself, just replace it with a random placeholder image and describe what you want to put there as a comment in Figma. Post your completed Figma design below. 

**Number of people: Unlimited
Volunteer Hours: 1 hour**

**Comment by WilliamShih1234** [comment]
https://docs.google.com/document/d/1wsDKsn9SlEPMWnygKEQAWQBrDiCNLfPAQ8ZqocGQBrg/edit

**Comment by WilliamShih1234** [comment]
https://www.figma.com/file/eoz1Kaocq7QJvfQok4Ub2i/Members-Page?node-id=0%3A1

**Comment by calvinfong26** [comment]
https://www.figma.com/file/RH8W0d1KUCkLZEUcbRO2wt/Members-Page?node-id=0%3A1
