### ISSUE TITLE
Web Development: Projects/Customers Section HTML Layout.

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/club-website-frontend#30]
Follow any design in #28, and create the HTML/CSS layout of a section about the projects we have completed before and the companies that are using the websites we developed. This section will be put at the bottom of the homepage. When you check out a figma design, make sure to click the present button on the top right corner to see the design's full effect.

**Number of people: unlimited
Volunteer Hours: 0.5 hour**

**Comment by yufanwang07** [comment]
End Product: (No animations)

[CustomersPage.zip](https://github.com/hicodingclub/club-website-frontend/files/5087253/CustomersPage.zip)
