### ISSUE TITLE
Member Page HTML Layout

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/club-website-frontend#6]
The hand-drawn layout is in the following link:
https://drive.google.com/open?id=1MaHhauleCgaIi13A2AEFYeFLWINLHWMV

**Comment by KL1217** [comment]
`<!DOCTYPE html>
<html>

    <head>
        <meta name="viewpoint" content="width=device-width, inital-scale=1.0">
        <link rel="stylesheet" href="style.css">
        <title>Memebrs</title>
        
    </head>

    <body>
        
        <img src="https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png"
            alt="Member Picture" class="p1"> 

        <div class="mission">
            <h1 style="background-color: rgb(56, 109, 189);">
                What we do</h1>
            <p style="background-color: rgb(56, 109, 189);">
                There should be a paragraph here</p>
            <div class="button">
                <button id="join" onclick="" 
                style="border-radius: 12px;">
                    JOIN US!</button>
                <span class="hovertext">
                    There should be text here</span>
            </div>        
        </div>

        <br>

        <h1 style="text-align: center; color: rgb(56, 109, 189);
            font-size: 42px;">
            Teams</h1>

        <div class="container">
            <div class="col" style="color: rgb(56, 109, 189);
            text-align: center;">
                <h2 style="font-size: 34px;">Web Development</h2>
                <div class="btn">
                    <button  class="btn1";>
                        <a href="https://www.google.com">
                            Link or Paragraph
                        </a></button></div>
            </div>
            <div class="col" style="color: rgb(56, 109, 189);
            text-align: center;">
                <h2 style="font-size: 34px;">UI Design</h2>
                <div class="btn">
                    <button class="btn2">
                        <a href="">Link or Paragraph
                        </a></button></div>
            </div>
            <div class="col" style="color: rgb(56, 109, 189);
            text-align: center;">
                <h2 style="font-size: 34px;">Quality Assurance</h2>
                <div  class="btn">
                    <button class="btn3">
                        <a href="">Link or Paragraph
                        </a></button></div>
            </div>
            <div class="col" style="color: rgb(56, 109, 189);
            text-align: center;">
                <h2 style="font-size: 34px;">Outreach</h2>
                <div  class="btn">
                    <button class="btn4">
                        <a href="">Link or Paragraph
                        </a></button></div>
            </div>
        </div>

        <br>
        <br>
        <br>
    
        <h1 style="text-align: center; color: rgb(56, 109, 189);
            font-size: 42px;">
            Board Members</h1>
        
        <div class="container">
            <div class="col" style="color: rgb(56, 109, 189);
            text-align: center;">
            <img src="https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png"
            alt="Member Picture" class="p2">
                <h2 style="font-size: 34px;">Member 1</h2>
                <div class="btn">
                    <button  class="btn1";>
                        <a href="https://www.google.com">
                            Link or Paragraph
                        </a></button></div>
            </div>
            <div class="col" style="color: rgb(56, 109, 189);
            text-align: center;">
            <img src="https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png"
            alt="Member Picture" class="p2">
                <h2 style="font-size: 34px;">Member 2</h2>
                <div class="btn">
                    <button class="btn2">
                        <a href="">Link or Paragraph
                        </a></button></div>
            </div>
        </div>

        <div class="container">
            <div class="col" style="color: rgb(56, 109, 189);
            text-align: center;">
            <img src="https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png"
            alt="Member Picture" class="p2">
                <h2 style="font-size: 34px;">Member 3</h2>
                <div class="btn">
                    <button  class="btn1";>
                        <a href="https://www.google.com">
                            Link or Paragraph
                        </a></button></div>
            </div>
            <div class="col" style="color: rgb(56, 109, 189);
            text-align: center;">
            <img src="https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png"
            alt="Member Picture" class="p2">
                <h2 style="font-size: 34px;">Member 4</h2>
                <div class="btn">
                    <button class="btn2">
                        <a href="">Link or Paragraph
                        </a></button></div>
            </div>
        </div>

    </body>

    <footer>
        © 2020 HiCoding Club. All rights reserved.
    </footer>

</html>`

**Comment by KL1217** [comment]
`*{
    box-sizing: border-box;
}

.mission{
    background-color: rgb(56, 109, 189);
    width: 50%;
    color: white;
    padding: 15px;
    text-align: center;
    border-radius: 15px;
    font-size: 36px;
}

.p1{
    width: 50%;
    float: right;
    height: 304px;
}

.button {
  position: relative;
  display: inline-block;
  
}

.button .hovertext{
  visibility: hidden;
  width: 120px;
  background-color: black;
  color: #fff;
  text-align: center;
  padding: 5px 0;
  border-radius: 6px;
  position: absolute;
  z-index: 1;
  font-size: 15px;
}

.button:hover .hovertext {
  visibility: visible;
}

#join{
    background-color: rgb(56, 109, 189);
    color: white;
    padding: 15px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}


.btn{
    text-align: center;
    padding: 5px; 
}

.btn1, .btn2, .btn3, .btn4{
    background-color: white;
    text-align: center;
    color: #3498DB;
    border: none;
    cursor: pointer;
}
.btn1:hover, .btn1:focus, .btn2:hover, .btn2:focus, .btn3:hover, .btn3:focus, .btn4:hover, .btn4:focus
{
    color: #2980B9;
}

.p2{
    background-color: rgb(56, 109, 189);
    width: 92%;
    padding: 15px;
}

.container{
    display: table;
    width: 100%;
}

.col{
    display: table-cell;
    padding: 16px;
    border: 1px solid black;
    border-radius: 20px;
    box-shadow: 
    2px 0 0 0 #888, 
    0 2px 0 0 #888, 
    2px 2px 0 0 #888,   
    2px 0 0 0 #888 inset, 
    0 2px 0 0 #888 inset;
}

@media only screen and (max-width: 600px){
    .col{
        display: block;
        width: 100%;
    }
}`
