### ISSUE TITLE
Contact Page HTML Layout

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/club-website-frontend#7]
Design the Contact Page HTML and CSS Layout. Do not worry about making it dynamic and connecting it to the backend. For pictures, if you don't have them, then just fill it in with a random picture for now (make sure to size it correctly tho), and we can replace it with the correct picture later. Make sure including information about:
* general contact
* each board member's contact
* board members' picture
* anything else you think fits

**Comment by ericsheng495** [comment]
<div class="container">
  <h1 style="text-align: center;"><span style="color: #333300;">Contact Us&nbsp;</span></h1>
<h3><strong><span style="color: #333300;">Board Members:</span></strong></h3>
<p style="text-align: center;"><span style="color: #333300;"><strong>Club President</strong></span></p>
<p style="padding-left: 30px; text-align: center;"><img style="display: block; margin-left: auto; margin-right: auto;" src="https://lh3.googleusercontent.com/proxy/QdU6zMWXoI8btZ-daLiBPOxMH8ObR1FaCJCwmw8JxbjNj4zwqQmXjNUEIdJb5NXrXmL-w8lKJmC1f35WG7CEODlM8Z5GByo-acbZ-7NkIoTOGQamrug" alt="" width="314" height="392" /><strong>Jack Liu</strong></p>
<p style="padding-left: 30px; text-align: center;"><strong><a class="Yh1nIb asUmFb AL18ce" href="mailto:toliujiayi@gmail.com" target="_blank" rel="noopener" data-tooltip="From user's Google profile" data-tooltip-position="top">toliujiayi@gmail.com</a></strong></p>
<p style="padding-left: 30px; text-align: center;">&nbsp;</p>
<p style="padding-left: 30px; text-align: center;">&nbsp;</p>
<p style="padding-left: 30px; text-align: center;"><img src="https://www.google.com/url?sa=i&amp;url=http%3A%2F%2Fcsis.msu.edu%2Fpeople%2Fjianguo-jack-liu&amp;psig=AOvVaw22yWcAGfEYAASo8oqmZpGa&amp;ust=1586582297894000&amp;source=images&amp;cd=vfe&amp;ved=0CAIQjRxqFwoTCLDZ8OmN3egCFQAAAAAdAAAAABBn" alt="" /><strong>Club Vice President</strong></p>
<p style="padding-left: 30px; text-align: center;"><strong><img src="https://d.newsweek.com/en/full/830619/per-xijinping-01-810459054.jpg?w=1600&amp;h=1600&amp;q=88&amp;f=0ff8903a420aec880cd2d3edad121ca5" alt="" width="330" height="330" /></strong></p>
<p style="padding-left: 30px; text-align: center;"><strong>Andrew Paul&nbsp;</strong></p>
<p style="padding-left: 30px; text-align: center;"><strong><a class="Yh1nIb asUmFb AL18ce" href="mailto:andrew.paul@warriorlife.net" target="_blank" rel="noopener" data-tooltip="From user's Google profile" data-tooltip-position="top">andrew.paul@warriorlife.net</a></strong></p>
<p style="padding-left: 30px; text-align: center;">&nbsp;</p>
<p style="padding-left: 30px; text-align: center;">&nbsp;</p>
<p style="padding-left: 30px; text-align: center;"><strong>Club Secretary</strong></p>
<p style="padding-left: 30px; text-align: center;"><strong><img src="https://upload.wikimedia.org/wikipedia/commons/5/59/Hu_Jintao_Cannes2011.jpg" alt="" width="305" height="366" /></strong></p>
<p style="padding-left: 30px; text-align: center;"><strong>Eric Sheng&nbsp;</strong></p>
<p style="padding-left: 30px; text-align: center;"><strong><a class="Yh1nIb asUmFb AL18ce" href="mailto:Eric.sheng495@gmail.com" target="_blank" rel="noopener" data-tooltip="From your Google Contacts" data-tooltip-position="top">Eric.sheng495@gmail.com</a></strong></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><strong>Potiential Customers:</strong></p>
<ul>
<li>Please contact&nbsp;<a class="Yh1nIb asUmFb AL18ce" href="mailto:toliujiayi@gmail.com" target="_blank" rel="noopener" data-tooltip="From user's Google profile" data-tooltip-position="top">toliujiayi@gmail.com</a>&nbsp;for more information.</li>
</ul>
<p>&nbsp;</p>
<p><strong>Future Club Members:</strong></p>
<ul>
<li>Please contact&nbsp;<a class="Yh1nIb asUmFb AL18ce" href="mailto:toliujiayi@gmail.com" target="_blank" rel="noopener" data-tooltip="From user's Google profile" data-tooltip-position="top">toliujiayi@gmail.com</a>&nbsp; for more information.</li>
</ul>
<p>&nbsp;</p>
<p>&nbsp;</p>
</div>

**Comment by ericsheng495** [comment]
https://docs.google.com/document/d/1_iZQvd48yAxwkoOnWhUIKpdYhUYB7GRHuut_CgBNV8s/edit?usp=sharing
